# POSTS
# GET /feed HTTP/1.1
# Host: localhost:8080

# POST /feed/new HTTP/1.1
# Host: localhost:8080 
# content-type: application/json

# {
#     "content": "Test Post #1", 
#     "user": "Byron Karlen"
# }

# PUT /feed/edit/646bb29cf75c397637e7d9b6 HTTP/1.1
# Host: localhost:8080 
# content-type: application/json

# {
#     "content": "Test Post #1",
#     "user": "N/A"
# }

DELETE /feed/delete/646e7a2db4b8ec9420644f71 HTTP/1.1
Host: localhost:8080 

# PUT /feed/like/646bb29cf75c397637e7d9b6 HTTP/1.1
# Host: localhost:8080 


# # USERS
# GET /users HTTP/1.1
# Host: localhost:8080

# POST /users/new HTTP/1.1
# Host: localhost:8080 
# content-type: application/json

# {
#     "username": "lilyneff", 
#     "password": "password"
# }

# DELETE /users/delete/646e6271ba37a0931dab4556 HTTP/1.1
# Host: localhost:8080

# PUT /users/edit/646c45fa5e8a511c0482cce8 HTTP/1.1
# Host: localhost:8080 
# content-type: application/json

# {
#     "username": "lilyneff2", 
#     "password": "newpassword"
# }

# POST /login HTTP/1.1
# Host: localhost:8080 
# content-type: application/json

# {
#     "username": "lilyneff3", 
#     "password": "password3"
# }

# GET /users HTTP/1.1
# Host: localhost:8080